# Generated by Django 5.2.5 on 2026-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_image_url', models.URLField(blank=True, help_text='Link to Wikimedia image of flag', max_length=500, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('gdp_usd_billions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_km2', models.IntegerField(blank=True, null=True)),
                ('official_language', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
