# Generated by Django 5.2.5 on 2026-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area_km2',
            field=models.IntegerField(blank=True, help_text='Area in square kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp_usd_billions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GDP in USD (Billions)', max_digits=10, null=True),
        ),
    ]
