# Generated by Django 5.2.5 on 2026-04-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_country_area_km2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='gdp_usd_billions',
        ),
        migrations.AddField(
            model_name='country',
            name='entry_type',
            field=models.CharField(default='Country', help_text='e.g. Country, Autonomous Region, Territory', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='fact',
            field=models.TextField(blank=True, help_text='An interesting fact about this place', null=True),
        ),
    ]
