# Generated by Django 5.2.5 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='vexillologist',
            name='mastered_flags',
            field=models.ManyToManyField(blank=True, related_name='mastered_by', to='frontend.country'),
        ),
    ]
